@echo off
ffmpeg -v error -i 7.mov  -f null -
ffmpeg -v error -i m03compCard..mov  -f null -
ffmpeg -v error -i m09compCard.mov  -f null -
ffmpeg -v error -i m105.mov  -f null -
ffmpeg -v error -i m107.mov  -f null -
ffmpeg -v error -i m108.mov  -f null -
ffmpeg -v error -i m201.mov  -f null -
ffmpeg -v error -i m202.mov  -f null -
ffmpeg -v error -i m203.mov  -f null -
ffmpeg -v error -i m205.mov  -f null -
ffmpeg -v error -i m207C.mov  -f null -
ffmpeg -v error -i m208.mov  -f null -
ffmpeg -v error -i m209.mov  -f null -
ffmpeg -v error -i m210.mov  -f null -
ffmpeg -v error -i m211.mov  -f null -
ffmpeg -v error -i m212.mov  -f null -
ffmpeg -v error -i m301.mov  -f null -
ffmpeg -v error -i m302.mov  -f null -
ffmpeg -v error -i m303.mov  -f null -
ffmpeg -v error -i m305.mov  -f null -
ffmpeg -v error -i m306.mov  -f null -
ffmpeg -v error -i m307.mov  -f null -
ffmpeg -v error -i m308.mov  -f null -
ffmpeg -v error -i m309.mov  -f null -
ffmpeg -v error -i m310.mov  -f null -
ffmpeg -v error -i m311.mov  -f null -
ffmpeg -v error -i m312.mov  -f null -
ffmpeg -v error -i m313.mov  -f null -
ffmpeg -v error -i m314.mov  -f null -
ffmpeg -v error -i trailer1.mov  -f null -
ffmpeg -v error -i trailer2.mov  -f null -